import Head from 'next/head';
import styles from '../styles/Home.module.css';


export default function Deploy() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Build an App With The Akash Blockchain</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <a href='/'>
                    <p>&larr; Go Back</p>
                </a>
                <h1>
               Deploy an App
                </h1>

                <div className={styles.grid}>
                    <a href="/TODO" className={styles.card}>
                        <h2>todo &rarr;</h2>
                        <p>todo</p>
                    </a>
                </div>
            </main>
        </div>
    );
}