import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Link from 'next/link'


export default function GUI() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Deploy an App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <a href='/Deploy'>
                    <p>&larr; Go Back</p>
                </a>
                <h1>
                    Deploy an App with the GUI
                </h1>

                <p>To use the GUI tool you will need to downlaod and install it. <br/>
                Once you have installed the tool please launch it. 
                    <br/> Download the tool 
                    <Link href="https://akashlytics.com/deploy" target="_blank">
                        <a> Here TODO ADD BETER LINK</a>
                    </Link> 
                </p>

                <div className={styles.grid}>
                    <a href="/GUISetup" className={styles.card}>
                        <h2>Success &rarr;</h2>
                        <p>I have installed the tool successfully</p>
                    </a>

                    <a href="/Help" className={styles.card}>
                        <h2>Error &rarr;</h2>
                        <p>I ran into an issue</p>
                    </a>
                </div>
            </main>
        </div>
    );
}