import Head from 'next/head';
import styles from '../styles/Home.module.css';


export default function GUICreateCert() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Deploy an App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <a href='/FundAccount'>
                    <p>&larr; Go Back</p>
                </a>
                <h1>
                    Create Your Certificate
                </h1>

                <p>
                    Certificates are what allow you to validate your idenetity to the providers you lease resrouces from.<br/>
                    For our walkthorugh we won't go into much detal but for now understand you will need one to deploy on the network.<br/>
                    To create a Certificate follow the steps blow:<br/>
                    1. In the top right hand corner of the window there is a large blue "Create Certificate" button.  Click it.<br/>
                    2. You will be prompted to enter the password you created when you setup the wallet.  Do so now.<br/>
                    3. Every transaction that effects the blockchain will require approval.  Go ahead and approve the create cert transaction.<br/>

                </p>

                <div className={styles.grid}>
                    <a href="/GUICreateDeployment" className={styles.card}>
                        <h2>Success &rarr;</h2>
                        <p>I see a serial number under the Certificate check mark.</p>
                    </a>

                    <a href="/Help" className={styles.card}>
                        <h2>Something Went Wrong &rarr;</h2>
                        <p>I don't see the serial number</p>
                    </a>
                </div>
            </main>
        </div>
    );
}