import Head from 'next/head';
import styles from '../styles/Home.module.css';


export default function GUIImportWallet() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Deploy an App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <a href='/GUISetup'>
                    <p>&larr; Go Back</p>
                </a>
                <h1>
                    Import an Existing Wallet
                </h1>

                <p>
                    To import a wallet follow these steps:<br/>
                    1. Click on the "Import Existing Account" button in the tool.<br/>
                    2. Next type the mnumonic seed phrase from your wallet in the provided box.<br/> 
                    3. You will need to name the wallet and put a password on it.  These settings<br/> 
                    will only apply inside this tool and will not effect the wallet on any other<br/> 
                    platform.<br/>
                    4. Click Next<br/> 
                </p>

                <div className={styles.grid}>
                    <a href="/FundAccount" className={styles.card}>
                        <h2>Success &rarr;</h2>
                        <p>It worked!  I can see my wallet in the tool.</p>
                    </a>

                    <a href="/Help" className={styles.card}>
                        <h2>Uh Oh &rarr;</h2>
                        <p>I seem to have run into an issue</p>
                    </a>
                </div>
            </main>
        </div>
    );
}