import Head from 'next/head';
import styles from '../styles/Home.module.css';


export default function GUISetup() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Deploy an App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <a href='/GUI'>
                    <p>&larr; Go Back</p>
                </a>
                <h1>
                    Deploy an App with the GUI
                </h1>

                <p>
                    Now that we have the tool installed we need to setup a wallet.<br/>
                    Go ahead and launch the tool.  From here you will see a screen asking <br/> 
                    you to create a wallet or import on. 
                </p>

                <div className={styles.grid}>
                    <a href="/GUICreateWallet" className={styles.card}>
                        <h2>Create Wallet &rarr;</h2>
                        <p>Choose this option if you don't have an AKT wallet yet.</p>
                    </a>

                    <a href="/GUIImportWallet" className={styles.card}>
                        <h2>Import Wallet &rarr;</h2>
                        <p>Choose this option if you already have a wallet with a mnumonic recovery phrase</p>
                    </a>
                </div>
            </main>
        </div>
    );
}