import Head from 'next/head';
import styles from '../styles/Home.module.css';


export default function Help() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Error Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <a href='/'>
                    <p>&larr; Go Back</p>
                </a>
                <h1>
                    Looks like you hit an error
                </h1>

                <p>If you ran into an issue we offer some addtional resources to help.</p>

                <div className={styles.grid}>
                    <a href="https://docs.akash.network/" className={styles.card}>
                        <h2>Docs &rarr;</h2>
                        <p>Link to the Docs site</p>
                    </a>

                    <a href="https://discord.com/invite/DxftX67" className={styles.card}>
                        <h2>Discord &rarr;</h2>
                        <p>Ask for help on our Discord</p>
                    </a>
                </div>
            </main>
        </div>
    );
}