import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mando's Flowchart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the Akash Network!
        </h1>

        <p className={styles.description}>
          What do you want to do?
        </p>

        <div className={styles.grid}>
          <a href="/Deploy" className={styles.card}>
            <h2>Deploy an App &rarr;</h2>
            <p>Deploy a containerized application to the akash network.</p>
          </a>

          <a href="/Provider" className={styles.card}>
            <h2>Become a Provider &rarr;</h2>
            <p>Sell compute resources to people on the network.</p>
          </a>

          <a
            href="/Build"
            className={styles.card}
          >
            <h2>Build an App With The Akash Blockchain &rarr;</h2>
            <p>Build an app that interacts with the Akash blockchain.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
