import Head from 'next/head';
import styles from '../styles/Home.module.css';


export default function Deploy() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Deploy an App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <a href='/'>
                    <p>&larr; Go Back</p>
                </a>
                <h1>
                    Under Construction
                </h1>
            </main>
        </div>
    );
}